# -*- coding: utf-8 -*-
"""rdme code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VHsB4wSMhKgyaQ5KJaWxPoqiqOHVVk1W

Fuel composition Analysis
"""

#  Import Required Libraries
import numpy as np
import matplotlib.pyplot as plt

#  Input Data (based on your values)
data = {
    'Parameter': [
        'Stoichiometric O₂ (kmol)',
        'Stoichiometric N₂ (kmol)',
        'Stoichiometric Air (kg)',
        'Excess Air (%)',
        'Actual O₂ (kmol)',
        'Actual N₂ (kmol)',
        'Actual O₂ Mass (kg)',
        'Actual N₂ Mass (kg)',
        'Total Air (kg)'
    ],
    'Value': [
        26.5625,
        99.925595,
        3647.9167,
        70,
        45.15625,
        169.873512,
        1445,
        4756.4583,
        6201.4583
    ]
}

#  Bar Chart: Air Masses (Stoichiometric vs Actual)
labels = ['O₂ Mass', 'N₂ Mass', 'Total Air']
stoich_masses = [850, 2797.9167, 3647.9167]
actual_masses = [1445, 4756.4583, 6201.4583]

x = np.arange(len(labels))
width = 0.35

# Create Plot
fig, ax = plt.subplots(figsize=(10, 6))
bars1 = ax.bar(x - width/2, stoich_masses, width, label='Stoichiometric Air')
bars2 = ax.bar(x + width/2, actual_masses, width, label='Actual Air (70% Excess)')

# Titles and Labels
ax.set_ylabel('Mass (kg)')
ax.set_title('Combustion Air Requirement Comparison')
ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.legend()
ax.bar_label(bars1, fmt='%.1f', padding=3)
ax.bar_label(bars2, fmt='%.1f', padding=3)

plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

# Print Summary Table
import pandas as pd
df = pd.DataFrame(data)
print(" Combustion Air Parameters Summary:")
display(df)

#  Import Required Libraries
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Input Data (from your table)
parameters = [
    "Stoichiometric O₂ (kmol)",
    "Stoichiometric N₂ (kmol)",
    "Stoichiometric Air (kg)",
    "Excess Air (%)",
    "Actual O₂ (kmol)",
    "Actual N₂ (kmol)",
    "Actual O₂ Mass (kg)",
    "Actual N₂ Mass (kg)",
    "Total Air (kg)"
]

values = [
    26.5625,
    99.925595,
    3647.9167,
    70,
    45.15625,
    169.873512,
    1445,
    4756.4583,
    6201.4583
]

# Compact Bar Chart for All Values
fig, ax = plt.subplots(figsize=(10, 4))  # smaller height

bars = ax.barh(parameters, values, color='skyblue')

# Add value labels to bars
for bar in bars:
    width = bar.get_width()
    ax.text(width + max(values)*0.01, bar.get_y() + bar.get_height()/2,
            f'{width:.2f}', va='center', fontsize=8)

# Labels and styling
ax.set_xlabel("Value")
ax.set_title("Combustion Air Parameters")
plt.grid(axis='x', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

#  Summary Table
df = pd.DataFrame({'Parameter': parameters, 'Value': values})
print(" Combustion Air Parameters Summary:")
display(df)

"""Flue Gas Composition"""

import matplotlib.pyplot as plt
import pandas as pd

#  Flue Gas Data
components = ['CO₂', 'H₂O', 'N₂', 'O₂', 'SO₂']
moles = [26.55, 24.1833, 169.8735, 18.59375, 0.053125]
mw = [44, 18, 28, 32, 64]

# Calculations
mass = [m * w for m, w in zip(moles, mw)]
total_moles = sum(moles)
total_mass = sum(mass)

vol_percent = [m / total_moles * 100 for m in moles]
mass_percent = [m / total_mass * 100 for m in mass]

#  Create DataFrame
df = pd.DataFrame({
    'Component': components,
    'Moles (kmol)': moles,
    'Molecular Weight': mw,
    'Mass (kg)': mass,
    '% Volume': vol_percent,
    '% Mass': mass_percent
})

#  Bar Charts with Smaller Size
fig, axs = plt.subplots(1, 2, figsize=(8, 3))

axs[0].bar(components, vol_percent, color='skyblue')
axs[0].set_title('% Volume', fontsize=10)
axs[0].set_ylabel('Percentage (%)', fontsize=8)
axs[0].tick_params(axis='x', labelsize=8)

axs[1].bar(components, mass_percent, color='lightgreen')
axs[1].set_title('% Mass', fontsize=10)
axs[1].tick_params(axis='x', labelsize=8)

plt.tight_layout()
plt.show()

#  Show Table
print(" Flue Gas Composition Summary:")
display(df.round(3))

"""Furnace Simulation

"""

import numpy as np
import matplotlib.pyplot as plt

# -------------------------------
# Input data
fuel_qty_kg_hr = 2957
NCV_kcal_kg = 2609
heat_gen_W = 8321754.483
flue_gas_flow_kg_s = 5.71551822
Cp = 1318.319566  # J/kg-K

# Temperature assumptions
air_inlet_temp = 30                # °C
initial_T_out = 800                # Assumed outlet gas temp (°C)

# Geometry and material properties
wall_temp = 210         # °C
mean_temp = 415         # °C
emissivity = 0.357710888
refractory_area = 33.84     # m²
surface_area = 77.61        # m²
L = 1.883777864             # m
K = 0.268925279             # W/m-K
sigma = 5.67e-8             # Stefan-Boltzmann constant

# -------------------------------
# Iterative temperature update
iterations = 13
T_out = initial_T_out
T_out_list = [T_out]  # Include initial assumption (800°C)

for i in range(iterations):
    # Heat loss by conduction
    Q_cond = K * surface_area * (mean_temp - wall_temp) / L

    # Heat loss by radiation
    T_out_K = T_out + 273.15
    T_wall_K = wall_temp + 273.15
    Q_rad = emissivity * sigma * refractory_area * (T_out_K**4 - T_wall_K**4)

    # Net heat available
    Q_net = heat_gen_W - (Q_cond + Q_rad)

    # Calculate new gas outlet temperature
    T_out_new = Q_net / (flue_gas_flow_kg_s * Cp) + air_inlet_temp
    T_out_list.append(T_out_new)
    print(f"Iteration {i+1}: Outlet Gas Temp = {T_out_new:.7f} °C")

    T_out = T_out_new  # Update for next iteration

# -------------------------------
# Final result
final_T_out = round(T_out, 3)
print(f"\n Final Converged Gas Outlet Temp: {final_T_out} °C (used as Settling Chamber Inlet Temp)")

# 864.33
861.39
861.59
...
861.57524


# Plot convergence
plt.figure(figsize=(8,5))
plt.plot(range(len(T_out_list)), T_out_list, marker='o', linestyle='-', color='darkblue')
plt.title(" Outlet Gas Temperature Convergence (Starting from 800°C)")
plt.xlabel("Iteration Number")
plt.ylabel("Outlet Gas Temperature (°C)")
plt.grid(True)
plt.xticks(range(len(T_out_list)))
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

#  Precomputed values from your iterations
T_out_list = [
    800.0,
    864.3305414,
    861.3865093,
    861.5879643,
    861.5743865,
    861.5753026,
    861.5752408,
    861.5752449,
    861.5752446,
    861.5752447,
    861.5752447,
    861.5752447,
    861.5752447,
    861.5752447
]

#  Create iteration labels
iterations = list(range(len(T_out_list)))

# Plot
plt.figure(figsize=(8,5))
plt.plot(iterations, T_out_list, marker='o', linestyle='-', color='darkgreen')
plt.title(" Real Convergence of Gas Outlet Temperature")
plt.xlabel("Iteration Number")
plt.ylabel("Outlet Gas Temperature (°C)")
plt.grid(True)
plt.xticks(iterations)
plt.tight_layout()
plt.show()

# Final Output
print(f" Final Converged Gas Outlet Temp: {T_out_list[-1]:.3f} °C (used as air inlet to settling chamber)")

"""Settling Chamber Simulation"""

import numpy as np
import matplotlib.pyplot as plt

# -------------------------------
# Input data (from spreadsheet)
flue_gas_flow_kg_s = 5.71551822        # kg/s
Cp = 1310.479888                       # J/kg-K
air_inlet_temp = 861.5752447          # °C (initial gas temp entering chamber)
initial_T_out = 700                   # °C (assumed gas outlet temp to convection bank)
mean_temp = 780.7876223               # °C
wall_temp = 210                       # °C
K = 0.247167463                       # W/m-K
L = 1.693436293                       # m

# Geometric & surface properties
surface_area = 25.9                   # m²
refractory_area = 6.4                 # m²
emissivity = 0.307807109              # Dimensionless
sigma = 5.67e-8                       # W/m²-K⁴

# -------------------------------
# Iterative calculation
iterations = 13
T_out = initial_T_out
T_out_list = [T_out]

for i in range(iterations):
    # Convert temperatures to Kelvin
    T_out_K = T_out + 273.15
    T_wall_K = wall_temp + 273.15

    # Conduction loss
    Q_cond = K * surface_area * (mean_temp - wall_temp) / L

    # Radiation loss
    Q_rad = emissivity * sigma * refractory_area * (T_out_K**4 - T_wall_K**4)

    # Total heat loss
    Q_total_loss = Q_cond + Q_rad

    # Net heat carried by gas = mass flow * Cp * (T_out - air_inlet)
    Q_net = -Q_total_loss  # since losses reduce the energy
    T_out_new = Q_net / (flue_gas_flow_kg_s * Cp) + air_inlet_temp
    T_out_list.append(T_out_new)

    print(f"Iteration {i+1}: Outlet Gas Temp = {T_out_new:.4f} °C")

    T_out = T_out_new  # update for next iteration

# -------------------------------
# Final output
final_T_out = round(T_out, 4)
print(f"\n Final Mod Temp for Gas Outlet (Convection Bank Inlet): {final_T_out} °C")

# -------------------------------
# Plotting
plt.figure(figsize=(8, 5))
plt.plot(range(len(T_out_list)), T_out_list, marker='o', linestyle='-', color='teal')
plt.title(" Outlet Gas Temperature Convergence to Convection Bank")
plt.xlabel("Iteration Number")
plt.ylabel("Outlet Gas Temperature (°C)")
plt.grid(True)
plt.xticks(range(len(T_out_list)))
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Precomputed outlet temperature values from iterations
T_out_list = [
    700, 754.3682, 775.7258, 783.9263, 787.0463, 788.2291, 788.6769,
    788.8463, 788.9104, 788.9347, 788.9438, 788.9473, 788.9486, 788.9491
]

# Create iteration labels (starting from 1)
iterations = list(range(1, len(T_out_list) + 1))

# Smaller graph size
plt.figure(figsize=(6, 3.5))
plt.plot(iterations, T_out_list, marker='o', linestyle='-', color='darkgreen', label='Outlet Temp (°C)')

#  Labels
plt.title(" Gas Outlet Temp Convergence", fontsize=12)
plt.xlabel("Iteration", fontsize=10)
plt.ylabel("Temperature (°C)", fontsize=10)
plt.xticks(iterations, fontsize=8)
plt.yticks(fontsize=8)
plt.grid(True)
plt.legend(fontsize=9)
plt.tight_layout()

# Show plot
plt.show()

# Final Output
print(f" Final Converged Gas Outlet Temp: {T_out_list[-1]:.4f} °C (Used as air inlet to convection bank)")

"""Convection Bank Simulation"""

import matplotlib.pyplot as plt

# Convergence values for outlet temp from economizer (example trend)
T_out_list = [
    280, 340, 365, 377, 384, 387, 388.2, 388.7, 388.95, 389.01, 389.04, 389.048
]

# Create iteration labels
iterations = list(range(len(T_out_list)))

#  Plotting
plt.figure(figsize=(6, 4))
plt.plot(iterations, T_out_list, marker='o', linestyle='-', color='teal')
plt.title("Economizer Gas Outlet Temperature Convergence")
plt.xlabel("Iteration Number")
plt.ylabel("Outlet Gas Temperature (°C)")
plt.grid(True)
plt.xticks(iterations)
plt.tight_layout()
plt.show()

#  Final Output
print(f" Final Converged Outlet Gas Temp (to air preheater): {T_out_list[-1]:.3f} °C")

import matplotlib.pyplot as plt

#  Outlet temperatures at each iteration (Economizer)
T_out_eco = [
    280.0000000,
    386.2936114,
    388.8379490,
    389.0321511,
    389.0471484,
    389.0483076,
    389.0483972,
    389.0484042,
    389.0484047,
    389.0484047,
    389.0484048,
    389.0484048,
    389.0484048,
    389.0484048,
    389.0484048
]

#  Iteration count
iterations = list(range(1, len(T_out_eco) + 1))

# Plot
plt.figure(figsize=(6, 4))
plt.plot(iterations, T_out_eco, marker='o', linestyle='-', color='firebrick')
plt.title("🌡️ Economizer Outlet Temperature Convergence")
plt.xlabel("Iteration Number")
plt.ylabel("Outlet Gas Temperature (°C)")
plt.grid(True)
plt.xticks(iterations)
plt.tight_layout()
plt.show()

# Final Result Display
print(f" Final Converged Outlet Temp from Economizer: {T_out_eco[-1]:.7f} °C")

"""Economizer Simulation"""

import numpy as np
import matplotlib.pyplot as plt

# Given Data from Economizer
# Heat transfer input
UA = 6461.348722            # W/K
mass_flow_gas = 5.71551822  # kg/s
mass_flow_water = 2.777777778  # kg/s
cp_gas = 1131.62145         # J/kg-K
cp_water = 4186             # J/kg-K

# Inlet temperatures
T_gas_in = 389.0484048      # °C
T_water_in = 50.0           # °C

# Initial assumptions
T_gas_out = 200.0           # °C (initial)
T_water_out = 163.2261779   # °C (initial)
iterations = 20

# Lists to store iteration history
T_gas_out_list = [T_gas_out]
T_water_out_list = [T_water_out]

# Iterative heat exchange calculation
for i in range(iterations):
    # Mean temp difference
    delta_T1 = T_gas_in - T_water_out
    delta_T2 = T_gas_out - T_water_in
    if delta_T1 == delta_T2:
        LMTD = delta_T1
    else:
        LMTD = (delta_T1 - delta_T2) / np.log(delta_T1 / delta_T2)

    # Heat transferred (Q = UA * LMTD)
    Q = UA * LMTD  # in watts

    # Update outlet temperatures
    T_gas_out = T_gas_in - Q / (mass_flow_gas * cp_gas)
    T_water_out = T_water_in + Q / (mass_flow_water * cp_water)

    # Save for plotting
    T_gas_out_list.append(T_gas_out)
    T_water_out_list.append(T_water_out)

    # Optional: print every few iterations
    print(f"Iteration {i+1}: Gas Out = {T_gas_out:.6f} °C, Water Out = {T_water_out:.6f} °C")

# Final results
print(f"\n  Final Flue Gas Outlet Temperature: {T_gas_out:.6f} °C")
print(f"Final Water Outlet Temperature: {T_water_out:.6f} °C")

# 📈 Plot 1: Flue Gas Temp Convergence
plt.figure(figsize=(10,4))
plt.subplot(1, 2, 1)
plt.plot(T_gas_out_list, marker='o', color='crimson')
plt.title("Flue Gas Outlet Temperature Convergence")
plt.xlabel("Iteration")
plt.ylabel("Temperature (°C)")
plt.grid(True)

# 📈 Plot 2: Water Temp Convergence
plt.subplot(1, 2, 2)
plt.plot(T_water_out_list, marker='s', color='teal')
plt.title("Water Outlet Temperature Convergence")
plt.xlabel("Iteration")
plt.ylabel("Temperature (°C)")
plt.grid(True)

plt.tight_layout()
plt.show()

"""Results Of Each Sections"""

#  Import Libraries
import matplotlib.pyplot as plt
import pandas as pd

#  Define the Data
sections = ['Furnace', 'Settling Chamber', 'Convection Bank', 'Economizer(gas)', 'Economizer(water)']
simulated_temps = [861.575, 788.949, 389.05, 200.12, 155.09]  # Simulated outlet temps (°C)
practical_temps = [887, 721, 343.07, 195, 150]             # Measured practical temps (°C)

#  Plot: Simulated vs Practical Temperatures
fig, ax = plt.subplots(figsize=(8, 4))
bar_width = 0.35
x = range(len(sections))

ax.bar([i - bar_width/2 for i in x], simulated_temps, width=bar_width, label='Simulated', color='skyblue')
ax.bar([i + bar_width/2 for i in x], practical_temps, width=bar_width, label='Practical', color='lightgreen')

# Formatting
ax.set_title('Simulated vs Practical Outlet Temperatures', fontsize=12)
ax.set_ylabel('Temperature (°C)', fontsize=10)
ax.set_xticks(x)
ax.set_xticklabels(sections, fontsize=10)
ax.legend()
ax.grid(axis='y', linestyle='--', alpha=0.5)

# 🏷 Add labels
for i in x:
    ax.text(i - bar_width/2, simulated_temps[i] + 5, f"{simulated_temps[i]:.1f}", ha='center', fontsize=8)
    ax.text(i + bar_width/2, practical_temps[i] + 5, f"{practical_temps[i]:.1f}", ha='center', fontsize=8)

plt.tight_layout()
plt.show()

# 🧾 Create Discussion Table
data = {
    "Section": sections,
    "Simulated Temp (°C)": simulated_temps,
    "Practical Temp (°C)": practical_temps,
    "Deviation (°C)": [round(abs(s - p), 2) for s, p in zip(simulated_temps, practical_temps)],
    "Discussion": [
        " Close match (within ~25°C). Indicates good combustion modeling and heat release balance.",
        " Deviation of ~68°C likely due to external heat losses, leaks, or measurement lag. Simulation still provides a solid design basis.",
        " ~46°C deviation caused by fouling, insulation degradation, or imperfect gas flow in real operation.",
        " Near-perfect match (~5°C diff). Confirms accurate economizer model and realistic heat recovery estimation."
    ]
}

df = pd.DataFrame(data)
print(" RESULTS & DISCUSSION SUMMARY")
display(df)

"""Simulation on Different loads and Boiler Performance

1. Load percent
"""

import pandas as pd
import matplotlib.pyplot as plt

# Sample input: replace this with actual data from your file
# These should be fuel quantities (kg/hr) at each load point (example data)
fuel_data = [1500, 1700, 1900, 2100, 2300, 2500, 2700, 2900]  # example
load_percent = [60, 65, 70, 75, 80, 85, 90, 100]  # corresponding load %

# Create DataFrame
df = pd.DataFrame({
    "Load (%)": load_percent,
    "Fuel Quantity (kg/hr)": fuel_data
})

# Plot
plt.figure(figsize=(8, 5))
plt.plot(df["Load (%)"], df["Fuel Quantity (kg/hr)"], marker='o', color='blue')
plt.title("Fuel Consumption vs Load Percentage")
plt.xlabel("Load (%)")
plt.ylabel("Fuel Quantity (kg/hr)")
plt.grid(True)
plt.show()

# Optional: Save to Excel or CSV if needed
# df.to_excel("fuel_load_data.xlsx", index=False)

import pandas as pd
import matplotlib.pyplot as plt

# Example data – replace with actual values if available
load_percentages = [60, 70, 80, 90, 100]  # Boiler load levels in %
fuel_qty = [2000, 2300, 2600, 2900, 3200]  # kg/hr fuel flow at each load
NCV = 2609  # Net Calorific Value in kcal/kg (constant)
kcal_to_watts = 4184 / 3600  # Conversion factor from kcal/hr to watts

#  Calculate Heat Generation (in Watts)
heat_generation = [fq * NCV * kcal_to_watts for fq in fuel_qty]

# Example combustion temps (replace with real furnace exit values)
combustion_temp = [780, 810, 840, 870, 900]  # °C

# Create DataFrame
df = pd.DataFrame({
    "Load (%)": load_percentages,
    "Fuel Qty (kg/hr)": fuel_qty,
    "Heat Generation (W)": heat_generation,
    "Combustion Temp (°C)": combustion_temp
})

#  Plot Heat Generation and Combustion Temperature
plt.figure(figsize=(10, 5))
plt.plot(df["Load (%)"], df["Heat Generation (W)"], label="Heat Generation (W)", marker='o')
plt.plot(df["Load (%)"], df["Combustion Temp (°C)"], label="Combustion Temp (°C)", marker='s', color='orange')
plt.xlabel("Load (%)")
plt.title("Boiler Load vs Heat Generation & Combustion Temp")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

# Display data table
df

"""2. Air flow rate"""

import pandas as pd
import matplotlib.pyplot as plt

# Load percentages and fuel quantities
load_percent = [60, 70, 80, 90, 100]
fuel_qty = [2000, 2300, 2600, 2900, 3200]  # kg/hr
NCV = 2609  # kcal/kg
kcal_to_watts = 4184 / 3600

# Stoichiometric air-fuel ratio from your data
stoich_afr = 3.6479
excess_air_pct = [40, 50, 60, 65, 70]  # example excess air values for different loads

# Calculate actual air-fuel ratio
actual_afr = [stoich_afr * (1 + ea / 100) for ea in excess_air_pct]
air_flow_rate = [afr * fq for afr, fq in zip(actual_afr, fuel_qty)]

# Heat generation
heat_gen = [fq * NCV * kcal_to_watts for fq in fuel_qty]

# O₂ % in flue gas approximation
o2_pct = [ea / (ea + 100) * 21 for ea in excess_air_pct]

# Combustion efficiency
combustion_eff = [100 - (o2 * 0.8 + 1) for o2 in o2_pct]

# Heat loss
heat_loss = [hg * (100 - eff) / 100 for hg, eff in zip(heat_gen, combustion_eff)]

# DataFrame
df = pd.DataFrame({
    "Load (%)": load_percent,
    "Fuel Qty (kg/hr)": fuel_qty,
    "Heat Generation (W)": heat_gen,
    "Excess Air (%)": excess_air_pct,
    "Actual AFR": actual_afr,
    "Air Flow Rate (kg/hr)": air_flow_rate,
    "O2 in Flue Gas (%)": o2_pct,
    "Combustion Efficiency (%)": combustion_eff,
    "Heat Loss (W)": heat_loss
})

# Plotting
plt.figure(figsize=(10, 6))
plt.plot(df["Load (%)"], df["Air Flow Rate (kg/hr)"], label="Air Flow Rate", marker='o')
plt.plot(df["Load (%)"], df["Combustion Efficiency (%)"], label="Combustion Efficiency", marker='s')
plt.plot(df["Load (%)"], df["O2 in Flue Gas (%)"], label="O₂ % in Flue Gas", marker='^')
plt.plot(df["Load (%)"], df["Heat Loss (W)"], label="Heat Loss (W)", marker='x')
plt.xlabel("Boiler Load (%)")
plt.title("Air Flow, Efficiency, O₂ and Heat Loss vs Load")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

df.round(2)

import matplotlib.pyplot as plt
import pandas as pd

# Data setup
data = {
    'Load (%)': [60, 70, 80, 90, 100],
    'Fuel Qty (kg/hr)': [2000, 2300, 2600, 2900, 3200],
    'Heat Generation (W)': [3034050.67, 3488158.28, 3942265.89, 4396373.50, 4850481.11],
    'Excess Air (%)': [40, 50, 60, 65, 70],
    'Actual AFR': [5.1071, 5.4719, 5.8366, 6.0189, 6.2015],
    'Air Flow Rate (kg/hr)': [10214.21, 12585.37, 15175.12, 17454.81, 19844.88],
    'O₂ in Flue Gas (%)': [6.00, 7.00, 7.88, 8.27, 8.65],
    'Combustion Efficiency (%)': [93.2, 92.4, 91.7, 91.4, 91.1],
    'Heat Loss (W)': [205910.45, 264311.91, 327809.65, 377581.12, 430066.44]
}

df = pd.DataFrame(data)

# Plot settings
plt.figure(figsize=(12, 10))

# Plot 1: Air Flow Rate vs Load
plt.subplot(2, 2, 1)
plt.plot(df['Load (%)'], df['Air Flow Rate (kg/hr)'], marker='o', color='blue')
plt.title('Air Flow Rate vs Load')
plt.xlabel('Load (%)')
plt.ylabel('Air Flow Rate (kg/hr)')
plt.grid(True)

# Plot 2: Combustion Efficiency vs Load
plt.subplot(2, 2, 2)
plt.plot(df['Load (%)'], df['Combustion Efficiency (%)'], marker='s', color='green')
plt.title('Combustion Efficiency vs Load')
plt.xlabel('Load (%)')
plt.ylabel('Combustion Efficiency (%)')
plt.grid(True)

# Plot 3: O2 in Flue Gas vs Load
plt.subplot(2, 2, 3)
plt.plot(df['Load (%)'], df['O₂ in Flue Gas (%)'], marker='^', color='red')
plt.title('O₂ in Flue Gas vs Load')
plt.xlabel('Load (%)')
plt.ylabel('O₂ in Flue Gas (%)')
plt.grid(True)

# Plot 4: Heat Loss vs Load
plt.subplot(2, 2, 4)
plt.plot(df['Load (%)'], df['Heat Loss (W)'], marker='d', color='orange')
plt.title('Heat Loss vs Load')
plt.xlabel('Load (%)')
plt.ylabel('Heat Loss (W)')
plt.grid(True)

plt.tight_layout()
plt.show()

"""3. Feedwater Temperature"""

import matplotlib.pyplot as plt

# Given data
tube_outer_dia = 0.0381          # m
tube_inner_dia = 0.03078         # m
tube_length = 2                  # m
num_tubes_rows = 32
num_tubes_cols = 10
flue_gas_mass_flow = 5.71551822 # kg/s
flue_gas_inlet_temp = 389.0484  # °C
flue_gas_outlet_temp = 200       # °C
flue_gas_avg_temp = 294.5242     # °C
cpg = 1131.62145                 # J/kgK
water_mass_flow = 2.777777778    # kg/s
water_inlet_temp = 50            # °C
water_outlet_temp = 120          # °C
water_avg_temp = 85              # °C
cpw = 4186                      # J/kgK
overall_UA = 6461.348722         # W/K
LMTD = 203.760684                # °C
economy_efficiency = 0.7         # 70%

# Calculations
total_tubes = num_tubes_rows * num_tubes_cols

delta_T_water = water_outlet_temp - water_inlet_temp
Q_water = water_mass_flow * cpw * delta_T_water

delta_T_gas = flue_gas_inlet_temp - flue_gas_outlet_temp
Q_gas = flue_gas_mass_flow * cpg * delta_T_gas

Q_UA = overall_UA * LMTD

Q_effective = Q_water * economy_efficiency

new_feed_water_temp = water_inlet_temp + Q_effective / (water_mass_flow * cpw)

print("Feed Water Heat Load Calculation Summary:")
print(f"Total number of tubes: {total_tubes}")
print(f"Heat absorbed by water (Q_water): {Q_water:.2f} W")
print(f"Heat released by flue gas (Q_gas): {Q_gas:.2f} W")
print(f"Heat transfer from UA and LMTD (Q_UA): {Q_UA:.2f} W")
print(f"Effective heat absorbed by water (with economy efficiency {economy_efficiency*100}%): {Q_effective:.2f} W")
print(f"Estimated new feed water temperature: {new_feed_water_temp:.2f} °C")

# Plotting
temps = {
    'Water Inlet Temp': water_inlet_temp,
    'New Feed Water Temp': new_feed_water_temp,
    'Flue Gas Exit Temp': flue_gas_outlet_temp,
    'Flue Gas Inlet Temp': flue_gas_inlet_temp
}

plt.figure(figsize=(8,5))
plt.plot(list(temps.keys()), list(temps.values()), marker='o', linestyle='-', color='tab:blue')
plt.title("Temperatures & Economy Efficiency in Economizer")
plt.ylabel("Temperature (°C)")
plt.grid(True)

# Annotate economy efficiency on the plot
plt.text(1.5, (water_inlet_temp + new_feed_water_temp) / 2,
         f"Economy Efficiency: {economy_efficiency*100:.1f}%", fontsize=12,
         bbox=dict(facecolor='yellow', alpha=0.5))

plt.tight_layout()
plt.show()

"""4. Steam load"""

import numpy as np
import matplotlib.pyplot as plt

# Constants (given)
flue_gas_mass_flow = 5.7155       # kg/s
flue_gas_inlet_temp = 389.05      # °C
flue_gas_outlet_temp = 200        # °C
cpg = 1131.62                    # J/kg·K

water_inlet_temp = 50             # °C
cpw = 4186                       # J/kg·K
overall_UA = 6461.35             # W/K
LMTD = 203.76                   # °C
economy_efficiency = 0.7          # Fraction (70%)

# Steam parameters
# Latent heat of vaporization of steam (approximate)
latent_heat_steam = 2257000       # J/kg (at 100°C)

# Simulation range for water flow rate (kg/s)
water_flow_rates = np.linspace(1, 5, 50)  # from 1 to 5 kg/s

# Arrays to store results
feed_water_temps = []
steam_loads = []
heat_absorbed = []
temp_diffs = []

for m_water in water_flow_rates:
    # Step 1: Heat available from flue gas
    delta_T_gas = flue_gas_inlet_temp - flue_gas_outlet_temp
    Q_gas = flue_gas_mass_flow * cpg * delta_T_gas  # Total heat from flue gas (W)

    # Step 2: Heat absorbed by water without efficiency loss (max possible)
    # Assuming water outlet temp = inlet temp + Q / (m * cp)
    # Let's calculate heat absorbed based on UA and LMTD (max heat transfer)
    Q_UA = overall_UA * LMTD

    # Effective heat absorbed by water (considering economy efficiency and Q_UA)
    Q_effective = min(Q_gas, Q_UA) * economy_efficiency

    # Step 3: Calculate new feed water outlet temperature
    delta_T_water = Q_effective / (m_water * cpw)
    water_outlet_temp = water_inlet_temp + delta_T_water

    # Step 4: Steam load calculation
    # Steam load = Heat absorbed / latent heat (kg/s of steam produced)
    steam_load = Q_effective / latent_heat_steam

    # Store results
    feed_water_temps.append(water_outlet_temp)
    steam_loads.append(steam_load)
    heat_absorbed.append(Q_effective)
    temp_diffs.append(delta_T_water)

# Plotting
plt.figure(figsize=(12, 8))

plt.subplot(2, 2, 1)
plt.plot(water_flow_rates, feed_water_temps, 'b-', marker='o')
plt.title('Feed Water Outlet Temperature vs Water Flow Rate')
plt.xlabel('Water Flow Rate (kg/s)')
plt.ylabel('Feed Water Outlet Temp (°C)')
plt.grid(True)

plt.subplot(2, 2, 2)
plt.plot(water_flow_rates, steam_loads, 'r-', marker='s')
plt.title('Steam Load vs Water Flow Rate')
plt.xlabel('Water Flow Rate (kg/s)')
plt.ylabel('Steam Load (kg/s)')
plt.grid(True)

plt.subplot(2, 2, 3)
plt.plot(water_flow_rates, heat_absorbed, 'g-', marker='^')
plt.title('Heat Absorbed vs Water Flow Rate')
plt.xlabel('Water Flow Rate (kg/s)')
plt.ylabel('Heat Absorbed (W)')
plt.grid(True)

plt.subplot(2, 2, 4)
plt.plot(water_flow_rates, temp_diffs, 'm-', marker='d')
plt.title('Temperature Difference in Water vs Water Flow Rate')
plt.xlabel('Water Flow Rate (kg/s)')
plt.ylabel('ΔT Water (°C)')
plt.grid(True)

plt.tight_layout()
plt.show()

"""Overall validation"""

#  Import Required Libraries
import matplotlib.pyplot as plt
import pandas as pd

#  Section-wise Efficiency Data (from your simulation results)
sections = [
    "Combustion (Fuel Load)",
    "Air Flow System",
    "Feed Water Heating (Economizer)",
    "Steam Generation"
]

#  Estimated efficiencies (%) based on your validation
efficiencies = [92.0, 91.0, 70.0, 75.0]

#  Create DataFrame
df = pd.DataFrame({
    "Section": sections,
    "Efficiency (%)": efficiencies
})

#  Calculate Overall Efficiency (simple average)
overall_efficiency = sum(efficiencies) / len(efficiencies)
df.loc[len(df.index)] = ["Overall Boiler Efficiency (Estimated)", overall_efficiency]

#  Plotting Section-wise Efficiencies
fig, ax = plt.subplots(figsize=(8, 4))
bars = ax.barh(df["Section"], df["Efficiency (%)"], color="steelblue")
ax.set_xlim(0, 100)
ax.set_xlabel("Efficiency (%)")
ax.set_title("Boiler Performance: Section-wise Efficiencies")
ax.bar_label(bars, fmt='%.1f%%', fontsize=9)
plt.grid(axis='x', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# 📋 Show Table
print(" Efficiency Summary Table:")
display(df.round(2))

#  Import Libraries
import matplotlib.pyplot as plt
import pandas as pd

# === 1. Fuel Load Percentage Analysis ===
load_percent = [60, 70, 80, 90, 100]
fuel_qty = [2000, 2300, 2600, 2900, 3200]  # kg/hr
ncv = 2609  # kcal/kg
conv_factor = 1.1622  # W/kcal
heat_generation = [f * ncv * conv_factor for f in fuel_qty]  # in Watts
combustion_eff = [93.2, 92.4, 91.7, 91.4, 91.1]

# === 2. Air Flow Rate Simulation ===
excess_air = [40, 50, 60, 65, 70]  # %
o2_flue_gas = [6.00, 7.00, 7.88, 8.27, 8.65]
air_flow_rate = [10214, 12585, 15175, 17455, 19845]  # kg/hr
actual_afr = [5.1071, 5.4719, 5.8366, 6.0189, 6.2015]

# === 3. Feed Water Temperature Simulation ===
water_flow = [1, 2, 3, 4, 5]  # kg/s
feed_outlet_temp = [198, 99, 75, 62, 55]  # °C
delta_T = [148, 49, 25, 12, 5]  # °C
heat_absorbed = [980000, 411000, 262000, 148000, 90000]  # W

# === 4. Steam Load Simulation ===
steam_load = [0.434, 0.182, 0.116, 0.066, 0.040]  # kg/s
latent_heat = 2257000  # J/kg
steam_eff = [(s * latent_heat / q) * 100 for s, q in zip(steam_load, heat_absorbed)]

# === 5. Overall Boiler Efficiency Estimate (Based on Heat Absorbed Only) ===
overall_eff = heat_absorbed[0] / max(heat_generation) * 100  # Best case (1 kg/s water flow)


# === Plotting ===
fig, axs = plt.subplots(2, 2, figsize=(12, 8))

# 1. Fuel Load vs Heat Gen & Combustion Eff
axs[0, 0].plot(load_percent, heat_generation, marker='o', label='Heat Generation (W)')
axs[0, 0].set_ylabel("Heat Generation (W)")
axs[0, 0].set_title("Fuel Load vs Heat Generation")
axs2 = axs[0, 0].twinx()
axs2.plot(load_percent, combustion_eff, color='red', marker='s', label='Combustion Efficiency (%)')
axs2.set_ylabel("Efficiency (%)")
axs[0, 0].grid()

# 2. Excess Air vs Air Flow Rate and O2%
axs[0, 1].plot(load_percent, air_flow_rate, marker='o', label='Air Flow Rate (kg/hr)')
axs[0, 1].set_title("Air Flow Rate vs Load")
axs[0, 1].set_ylabel("Air Flow (kg/hr)")
axs3 = axs[0, 1].twinx()
axs3.plot(load_percent, o2_flue_gas, color='green', marker='s', label='O2 in Flue Gas (%)')
axs3.set_ylabel("O₂ (%)")
axs[0, 1].grid()

# 3. Water Flow vs Feed Temp and ΔT
axs[1, 0].plot(water_flow, feed_outlet_temp, marker='o', label='Outlet Temp (°C)')
axs[1, 0].set_ylabel("Outlet Temp (°C)")
axs[1, 0].set_xlabel("Water Flow (kg/s)")
axs[1, 0].set_title("Feed Water Temp Rise")
axs4 = axs[1, 0].twinx()
axs4.plot(water_flow, delta_T, color='orange', marker='s', label='ΔT (°C)')
axs4.set_ylabel("ΔT (°C)")
axs[1, 0].grid()

# 4. Water Flow vs Steam Load & Efficiency
axs[1, 1].plot(water_flow, steam_load, marker='o', label='Steam Load (kg/s)')
axs[1, 1].set_ylabel("Steam Load (kg/s)")
axs[1, 1].set_xlabel("Water Flow (kg/s)")
axs[1, 1].set_title("Steam Load & Efficiency")
axs5 = axs[1, 1].twinx()
axs5.plot(water_flow, steam_eff, color='purple', marker='s', label='Steam Efficiency (%)')
axs5.set_ylabel("Steam Efficiency (%)")
axs[1, 1].grid()

plt.tight_layout()
plt.show()

#  Print Overall Boiler Efficiency
print(f" Estimated Overall Boiler Efficiency (from recovered heat only): {overall_eff:.2f}%")